before:
  hooks:
    - go mod download

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: shellbear
    name: web-watcher

dockers:
  - ids:
      - web-watcher
    dockerfile: Dockerfile.cgo
    image_templates:
      - "docker.pkg.github.com/shellbear/web-watcher/web-watcher:{{ .Tag }}"
      - "docker.pkg.github.com/shellbear/web-watcher/web-watcher:latest"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.name={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
